theme: jekyll-theme-minimal

logo: ./profile.jpg
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mohammed Al Farhan
description: Computer Scientist <br> <a href="./mohammed_alfarhan_resume_20220224.pdf">Resume</a> <br><br> <a href="https://twitter.com/ibomohsin"><img width="10%" height="10%" src="https://img.icons8.com/ios-filled/50/000000/twitter.png"/></a> <a href='mailto:ibo.mohsin@gmail.com'><img width="10%" height="10%" src="https://img.icons8.com/external-kiranshastry-solid-kiranshastry/64/000000/external-email-interface-kiranshastry-solid-kiranshastry.png"/></a>
show_downloads: false
github:
  is_project_page: false
