theme: jekyll-theme-minimal
logo: ./avatar.jpg
title: Mohammed<br>Al Farhan
description: Computer Scientist<br>
<a href="./mohammed_alfarhan_resume_20220224.pdf">Resume</a><br><br>
<a href="https://www.linkedin.com/in/mohammed-al-farhan-08669122a/"><img width="10%" height="10%" src="https://img.icons8.com/external-justicon-flat-justicon/64/000000/external-linkedin-social-media-justicon-flat-justicon.png"/></a>
<a href="https://scholar.google.com/citations?hl=en&user=CX9cRR8AAAAJ&view_op=list_works&sortby=pubdate"<img width="10%" height="10%" src="https://img.icons8.com/ios-filled/50/000000/google-scholar--v2.png"/></a>
<a href="https://github.com/farhanma"><img width="10%" height="10%" src="https://img.icons8.com/ios-filled/50/000000/github.png"/></a>
<a href='mailto:alfarhanmah@gmail.com'><img width="10%" height="10%" src="https://img.icons8.com/external-kiranshastry-solid-kiranshastry/64/000000/external-email-interface-kiranshastry-solid-kiranshastry.png"/></a>
show_downloads: false
github:
  is_project_page: false
